# Generated by Django 4.1.6 on 2023-05-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='workshop_license',
            field=models.CharField(max_length=20),
        ),
    ]
