# Generated by Django 4.1.6 on 2023-05-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_mechanic_workshop_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('vehicle_num', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('msg', models.CharField(max_length=20)),
            ],
        ),
    ]
