# Generated by Django 4.1.6 on 2023-05-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_book_service_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='accept_serv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('vehicle_num', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('msg', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('accept', 'accept'), ('reject', 'reject')], max_length=10)),
            ],
        ),
    ]
