# Generated by Django 4.1.6 on 2023-05-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_accept_serv'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_service',
            name='status',
            field=models.CharField(choices=[('accept', 'accept'), ('reject', 'reject')], default=111, max_length=10),
            preserve_default=False,
        ),
    ]
