# Generated by Django 4.1.6 on 2023-05-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_book_service_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=25)),
                ('admin_pass', models.CharField(max_length=20)),
            ],
        ),
    ]
