# Generated by Django 4.1.7 on 2023-05-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_user_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='mech_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('user_email', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=25)),
                ('message', models.CharField(max_length=25)),
            ],
        ),
    ]
