# Generated by Django 4.1.7 on 2023-06-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_mech_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_service',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
