# Generated by Django 4.1.7 on 2023-06-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_book_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_service',
            name='status',
            field=models.CharField(choices=[('accept', 'accept'), ('reject', 'reject'), ('complete', 'complete'), ('cancel', 'cancel')], max_length=10),
        ),
    ]
